---
title: "Expression rate of b-cat and Twist2"
author: "Seok-hyung Kim"
date: "2024-03-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R package uploading
```{r message=FALSE, warning=FALSE}
library(readxl)
library(ggplot2)
library(dplyr)
```

## Preparation of Desmoid data with B-cateinin and Twist2 IHC score
```{r warning=FALSE, message=FALSE}
B_cat=read_excel("../SHK_scoring/Beta-catenin.xlsx", sheet = 'Desmoid_SHK') 
B_cat <- B_cat[, c(4,5,7,9,11,12)] %>% filter(Dx=="Desmoid")
B_cat$`Percentage-2` <- ifelse(is.na(B_cat$`Percentage-2`), 0, B_cat$`Percentage-2`)
B_cat$`Percentage-3` <- ifelse(is.na(B_cat$`Percentage-3`), 0, B_cat$`Percentage-3`)
B_cat$Per.total <- B_cat[[3]] + B_cat[[4]] + B_cat[[5]]
B_cat$B_cat.re <- ifelse(B_cat$IHC_score > 0.5, "B_cat.pos", "B_cat.neg")


TWIST2=read_excel("../SHK_scoring/TWIST2.xlsx", sheet = 'Desmoid_SHK')
colnames(TWIST2)[12] <- "IHC_score"
TWIST2<- TWIST2 %>% filter(Dx=="Desmoid") %>% select(c(4,5,7,9,11,12))
TWIST2$`Percentage-2` <- ifelse(is.na(TWIST2$`Percentage-2`), 0, TWIST2$`Percentage-2`)
TWIST2$`Percentage-3` <- ifelse(is.na(TWIST2$`Percentage-3`), 0, TWIST2$`Percentage-3`)
TWIST2$Per.total <- TWIST2[[3]] + TWIST2[[4]] + TWIST2[[5]]
TWIST2$TWIST2.re <- ifelse(TWIST2$IHC_score > 22.5, "TWIST2_pos", "TWIST2.neg")
```

## Boxplot showing expression percentage of B-catenin and Twist2
```{r}
ds = rbind(B_cat[, c(1,2,6,7)], TWIST2[,c(1,2,6,7)])
# ds <- bind_rows(B_cat[, c(5,6)], TWIST2[, c(4,5)])
ds$marker <- c(rep("B_cat", 83), rep("TWIST2", 83))

ggplot(ds, aes(x = marker, y = Per.total)) + 
  geom_boxplot()+
  ylim(0,100)+
  geom_jitter(shape=16, size=2, position=position_jitter(0.15))+
  ggtitle("Expression percentage")+ 
  theme_classic()
# ggsave("Result/2024_03/Expession_percentage_Beta.catenin_TWIST2.pdf")
```

```{r}
t.test(ds$Per.total ~ ds$marker)
```

```{r}
ds2 <- cbind(B_cat[ ,'B_cat.re'], TWIST2[,'TWIST2.re'])
table(ds2$B_cat.re, ds2$TWIST2.re)
```

```{r}
B_cat %>% filter(B_cat.re =="B_cat.neg") %>% pull('S-ID') -> B_cat.neg.case
ds3 <- ds %>% filter(ds$`S-ID` %in% B_cat.neg.case)

ggplot(ds3, aes(x = marker, y = Per.total)) + 
  geom_boxplot()+
  ylim(0,100)+
  geom_jitter(shape=16, size=2, position=position_jitter(0.15))+
  ggtitle("Expression percentage in B-catenin negative desmoid")+ 
  theme_classic()
```


## Preparation of Scar data with B-cateinin and Twist2 IHC score
```{r}
B_cat=read_excel("../SHK_scoring/Beta-catenin.xlsx", sheet = 'Desmoid_SHK') 
B_cat <- B_cat[, c(5,7,9,11,12)] %>% filter(Dx=="Scar")
B_cat$`Percentage-2` <- ifelse(is.na(B_cat$`Percentage-2`), 0, B_cat$`Percentage-2`)
B_cat$`Percentage-3` <- ifelse(is.na(B_cat$`Percentage-3`), 0, B_cat$`Percentage-3`)
B_cat$Per.total <- B_cat[[2]] + B_cat[[3]] + B_cat[[4]]
B_cat$B_cat.re <- ifelse(B_cat$IHC_score > 0.5, "B_cat.pos", "B_cat.neg")


TWIST2=read_excel("../SHK_scoring/TWIST2.xlsx", sheet = 'Desmoid_SHK')
colnames(TWIST2)[12] <- "IHC_score"
TWIST2<- TWIST2 %>% filter(Dx=="Scar") %>% select(c(7,9,11,12))
TWIST2$`Percentage-2` <- ifelse(is.na(TWIST2$`Percentage-2`), 0, TWIST2$`Percentage-2`)
TWIST2$`Percentage-3` <- ifelse(is.na(TWIST2$`Percentage-3`), 0, TWIST2$`Percentage-3`)
TWIST2$Per.total <- TWIST2[[1]] + TWIST2[[2]] + TWIST2[[3]]
TWIST2$TWIST2.re <- ifelse(TWIST2$IHC_score > 22.5, "TWIST2_pos", "TWIST2.neg")

ds4 <- cbind(B_cat[ ,'B_cat.re'], TWIST2[,'TWIST2.re'])
table(ds4$B_cat.re, ds4$TWIST2.re)
```

